### ISSUE TITLE
Details about a file

### ISSUE THREAD

**Issue by FatemaTabassum** [ISU-PAAL/DL-VD-Empirical-Study#1]
I am looking at the getset_cew.py file that is under the following directory

cross_sections -> code -> getset_cwe

In the notebook, I see the following line

tree = etree.parse("/home/<ANONYMOUS>/code/linevd/storage/external/1000.xml")

But I could not find any file named 1000.xml file.  Maybe you can add some details about this file

**Comment by bstee615** [comment]
Thank you for opening this issue😊

I believe this is the XML file of CWE Research Concepts, downloaded from this page: https://cwe.mitre.org/data/downloads.html
Here is the direct link to download the file: https://cwe.mitre.org/data/xml/views/1000.xml.zip
