### ISSUE TITLE
Could you please reshare the data link in the file models/Devign_ReVeal/code/README_data.md

### ISSUE THREAD

**Issue by PeterPanYuchen** [ISU-PAAL/DL-VD-Empirical-Study#2]
Thanks for your detailed work which helped me a lot. 

The link _[https://git.las.iastate.edu/<ANONYMOUS>/ReVeal](https://git.las.iastate.edu/%3CANONYMOUS%3E/ReVeal)_ in the file [models/Devign_ReVeal/code/README_data.md](https://github.com/ISU-PAAL/DL-VD-Empirical-Study/blob/main/models/Devign_ReVeal/code/README_data.md) is broken, could you please reshare it?

Thanks so much!

**Comment by bstee615** [comment]
Sure, the code inside that directory (https://github.com/ISU-PAAL/DL-VD-Empirical-Study/tree/main/models/Devign_ReVeal/code) should be a copy of the code in that repo, the final version which was used for our experiments -- during development, this was a pointer to our private fork of the repo. I edited the readme to remove this stale link. Please feel free to reach out with any questions.
